// Jura
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

// GTM Actions
export const GTM_TRACK_PAGE_CHANGE = 'GTM_TRACK_PAGE_CHANGE';
